<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page session="false" %>
<html>
<head>
	<title>Test Page</title>
</head>
<body>
<h1>Test page with links.</h1>
<h2>Anchor links (&lt;a&gt;)</h2>
<div>
	<a href="testHome">Simple anchor without </a>
</div>
<div>
	<a>Anchor without HREF</a>
</div>
<div>
	<a href="testPageWithLinks">Recursive anchor</a>
</div>
<div>
	<script>
		document.write('<a href="testHome">Anchor generated by JS immediately</a>');
	</script>
</div>
<div id="anchor-with-timeout-holder">
	<script>
		var appendAnchor = function() {
			var holder = document.getElementById('anchor-with-timeout-holder');
			holder.innerHTML += '<a href="testHome">Anchor generated by JS after 400ms</a>';
		};
		window.setTimeout(appendAnchor, 400);
	</script>
</div>
<!-- TODO add another link types -->
</body>
</html>
